## Random Forest Feature Importance
In this notebook we use random forest modeling (an ensemble method building upon decision trees) to evaluate the feature importance of our dataset. We are doing this instead of calculating feature importance on our knn model because we have been unable to calculate feature importance for the divorce dataset on the knn model. We are using the random forest model from SciKit Learn.

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
# Import divorce data
divorce = pd.read_csv('data/divorce_data.csv',sep=';')

# Processing features:
X = divorce.drop('Divorce',axis=1) # .dropna() - dataset has no missing values
t = divorce['Divorce']

# Display summary statistics for the features
print(f"These are the summary statistics for the features:\n {X.describe()}")
print("--------------------------------------------------------------------")
print(f"This is the number of rows in the dataset: {len(X)}")
print("--------------------------------------------------------------------")
print(f"This is the number of unique values in each column:\n {X.nunique()}")

These are the summary statistics for the features:
                Q1          Q2          Q3          Q4          Q5          Q6  \
count  170.000000  170.000000  170.000000  170.000000  170.000000  170.000000
mean     1.776471    1.652941    1.764706    1.482353    1.541176    0.747059
std      1.627257    1.468654    1.415444    1.504327    1.632169    0.904046
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000
25%      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000
50%      2.000000    2.000000    2.000000    1.000000    1.000000    0.000000
75%      3.000000    3.000000    3.000000    3.000000    3.000000    1.000000
max      4.000000    4.000000    4.000000    4.000000    4.000000    4.000000

               Q7          Q8          Q9         Q10  ...         Q45  \
count  170.000000  170.000000  170.000000  170.000000  ...  170.000000
mean     0.494118    1.452941    1.458824    1.576471  ...    2.458824
std      0.898698    1.546371    1.557976    1.421529  ...    1.499925
min      0.000000    0.000000    0.000000    0.000000  ...    0.000000
25%      0.000000    0.000000    0.000000    0.000000  ...    1.000000
50%      0.000000    1.000000    1.000000    2.000000  ...    3.000000
75%      1.000000    3.000000    3.000000    3.000000  ...    4.000000
max      4.000000    4.000000    4.000000    4.000000  ...    4.000000

              Q46         Q47         Q48         Q49         Q50         Q51  \
count  170.000000  170.000000  170.000000  170.000000  170.000000  170.000000
mean     2.552941    2.270588    2.741176    2.382353    2.429412    2.476471
std      1.371786    1.586841    1.137348    1.511587    1.405090    1.260238
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000
25%      2.000000    1.000000    2.000000    1.000000    1.000000    2.000000
50%      3.000000    2.000000    3.000000    3.000000    2.000000    3.000000
75%      4.000000    4.000000    4.000000    4.000000    4.000000    4.000000
max      4.000000    4.000000    4.000000    4.000000    4.000000    4.000000

              Q52         Q53         Q54
count  170.000000  170.000000  170.000000
mean     2.517647    2.241176    2.011765
std      1.476537    1.505634    1.667611
min      0.000000    0.000000    0.000000
25%      1.000000    1.000000    0.000000
50%      3.000000    2.000000    2.000000
75%      4.000000    4.000000    4.000000
max      4.000000    4.000000    4.000000

[8 rows x 54 columns]
--------------------------------------------------------------------
This is the number of rows in the dataset: 170
--------------------------------------------------------------------
This is the number of unique values in each column:
 Q1     5
Q2     5
Q3     5
Q4     5
Q5     5
Q6     5
Q7     5
Q8     5
Q9     5
Q10    5
Q11    5
Q12    5
Q13    5
Q14    5
Q15    5
Q16    5
Q17    5
Q18    5
Q19    5
Q20    5
Q21    5
Q22    5
Q23    5
Q24    5
Q25    5
Q26    5
Q27    5
Q28    5
Q29    5
Q30    5
Q31    5
Q32    5
Q33    5
Q34    5
Q35    5
Q36    5
Q37    5
Q38    5
Q39    5
Q40    5
Q41    5
Q42    5
Q43    5
Q44    5
Q45    5
Q46    5
Q47    5
Q48    5
Q49    5
Q50    5
Q51    5
Q52    5
Q53    5
Q54    5
dtype: int64

#### Train-Test Split

In [15]:
# Done with sklearn
from sklearn.model_selection import train_test_split

# Split the data into training and validation sets
train_X, val_X, train_y, val_y = train_test_split(X, t, test_size=0.33, random_state=42)

# Print the train X and y shapes
print(f"Train X shape: {train_X.shape}")
print(f"Train y shape: {train_y.shape}")

# Print the summary statistics of the training features and testing features
print(f"Train X summary statistics:\n {train_X.describe()}")
print("--------------------------------------------------------------------")
print(f"Test X summary statistics:\n {val_X.describe()}")

Train X shape: (113, 54)
Train y shape: (113,)
Train X summary statistics:
                Q1          Q2          Q3          Q4          Q5          Q6  \
count  113.000000  113.000000  113.000000  113.000000  113.000000  113.000000
mean     1.672566    1.566372    1.690265    1.433628    1.477876    0.769912
std      1.589264    1.387933    1.382800    1.469184    1.581688    0.906414
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000
25%      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000
50%      2.000000    1.000000    2.000000    1.000000    1.000000    1.000000
75%      3.000000    3.000000    3.000000    3.000000    3.000000    1.000000
max      4.000000    4.000000    4.000000    4.000000    4.000000    4.000000

               Q7          Q8          Q9         Q10  ...         Q45  \
count  113.000000  113.000000  113.000000  113.000000  ...  113.000000
mean     0.477876    1.371681    1.398230    1.539823  ...    2.371681
std      0.856669    1.465037    1.497258    1.420735  ...    1.501158
min      0.000000    0.000000    0.000000    0.000000  ...    0.000000
25%      0.000000    0.000000    0.000000    0.000000  ...    1.000000
50%      0.000000    1.000000    1.000000    2.000000  ...    3.000000
75%      1.000000    3.000000    3.000000    3.000000  ...    4.000000
max      4.000000    4.000000    4.000000    4.000000  ...    4.000000

              Q46         Q47         Q48         Q49         Q50         Q51  \
count  113.000000  113.000000  113.000000  113.000000  113.000000  113.000000
mean     2.575221    2.238938    2.761062    2.371681    2.433628    2.530973
std      1.387478    1.582687    1.159390    1.477176    1.355387    1.232526
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000
25%      2.000000    1.000000    2.000000    1.000000    1.000000    2.000000
50%      3.000000    3.000000    3.000000    3.000000    2.000000    3.000000
75%      4.000000    4.000000    4.000000    4.000000    4.000000    4.000000
max      4.000000    4.000000    4.000000    4.000000    4.000000    4.000000

              Q52         Q53         Q54
count  113.000000  113.000000  113.000000
mean     2.522124    2.318584    1.946903
std      1.439850    1.483634    1.635765
min      0.000000    0.000000    0.000000
25%      1.000000    1.000000    0.000000
50%      3.000000    3.000000    2.000000
75%      4.000000    4.000000    4.000000
max      4.000000    4.000000    4.000000

[8 rows x 54 columns]
--------------------------------------------------------------------
Test X summary statistics:
               Q1         Q2         Q3         Q4         Q5         Q6  \
count  57.000000  57.000000  57.000000  57.000000  57.000000  57.000000
mean    1.982456   1.824561   1.912281   1.578947   1.666667   0.701754
std     1.695490   1.616023   1.479391   1.580544   1.735484   0.905635
min     0.000000   0.000000   0.000000   0.000000   0.000000   0.000000
25%     0.000000   0.000000   0.000000   0.000000   0.000000   0.000000
50%     3.000000   2.000000   2.000000   2.000000   1.000000   0.000000
75%     4.000000   3.000000   3.000000   3.000000   3.000000   1.000000
max     4.000000   4.000000   4.000000   4.000000   4.000000   3.000000

              Q7         Q8         Q9        Q10  ...        Q45        Q46  \
count  57.000000  57.000000  57.000000  57.000000  ...  57.000000  57.000000
mean    0.526316   1.614035   1.578947   1.649123  ...   2.631579   2.508772
std     0.983893   1.698259   1.679151   1.432919  ...   1.495608   1.351227
min     0.000000   0.000000   0.000000   0.000000  ...   0.000000   0.000000
25%     0.000000   0.000000   0.000000   0.000000  ...   1.000000   2.000000
50%     0.000000   1.000000   1.000000   2.000000  ...   3.000000   3.000000
75%     1.000000   3.000000   3.000000   3.000000  ...   4.000000   4.000000
max     4.000000   4.000000   4.000000   4.000000  ...   4.000000   4.000000

             Q47        Q48        Q49        Q50        Q51        Q52  \
count  57.000000  57.000000  57.000000  57.000000  57.000000  57.000000
mean    2.333333   2.701754   2.403509   2.421053   2.368421   2.508772
std     1.607275   1.101378   1.590818   1.511236   1.317893   1.559794
min     0.000000   0.000000   0.000000   0.000000   0.000000   0.000000
25%     1.000000   2.000000   1.000000   1.000000   2.000000   1.000000
50%     2.000000   3.000000   3.000000   2.000000   2.000000   3.000000
75%     4.000000   4.000000   4.000000   4.000000   3.000000   4.000000
max     4.000000   4.000000   4.000000   4.000000   4.000000   4.000000

             Q53        Q54
count  57.000000  57.000000
mean    2.087719   2.140351
std     1.550123   1.736567
min     0.000000   0.000000
25%     1.000000   0.000000
50%     2.000000   2.000000
75%     4.000000   4.000000
max     4.000000   4.000000

[8 rows x 54 columns]

#### Random Forest Model
Here we'll instantiate and train a Random Forest model using SciKit Learn's RandomForestClassifier. We'll use default parameters.

In [29]:
from sklearn.ensemble import RandomForestClassifier

# NOTE: uncomment the following line if you want to have random datasets each time you run the code
# train_X, val_X, train_y, val_y = train_test_split(X, t, test_size=0.33)

rf = RandomForestClassifier(n_estimators=100, max_depth=5, random_state=42)

# Fit the model
rf.fit(train_X, train_y)

# Print the training and testing accuracies
print(f"Train accuracy: {rf.score(train_X, train_y)}")
print(f"Test accuracy: {rf.score(val_X, val_y)}")

# Get feature importances from our random forest model
importances = rf.feature_importances_

# Display the importances sorted in descending order in a dataframe
feature_importances = pd.DataFrame({
    'feature':train_X.columns,
    'importance':importances
}).sort_values('importance',ascending=False)

display(feature_importances)

Train accuracy: 1.0
Test accuracy: 0.9824561403508771

   feature  importance
17     Q18    0.144867
18     Q19    0.103354
39     Q40    0.097450
35     Q36    0.086462
10     Q11    0.070627
29     Q30    0.067510
16     Q17    0.057020
19     Q20    0.041687
15     Q16    0.038775
13     Q14    0.037750
38     Q39    0.035228
25     Q26    0.031312
4       Q5    0.029529
27     Q28    0.027537
8       Q9    0.020988
28     Q29    0.019647
3       Q4    0.010394
40     Q41    0.010090
34     Q35    0.008947
26     Q27    0.008740
24     Q25    0.008667
20     Q21    0.008222
53     Q54    0.008195
1       Q2    0.003993
2       Q3    0.002872
32     Q33    0.002644
7       Q8    0.002637
48     Q49    0.002006
51     Q52    0.001510
43     Q44    0.001428
12     Q13    0.001352
14     Q15    0.001352
49     Q50    0.001039
5       Q6    0.001003
52     Q53    0.000979
44     Q45    0.000973
36     Q37    0.000943
23     Q24    0.000673
33     Q34    0.000376
0       Q1    0.000352
41     Q42    0.000347
37     Q38    0.000270
11     Q12    0.000239
47     Q48    0.000011
22     Q23    0.000000
42     Q43    0.000000
9      Q10    0.000000
45     Q46    0.000000
46     Q47    0.000000
31     Q32    0.000000
30     Q31    0.000000
50     Q51    0.000000
21     Q22    0.000000
6       Q7    0.000000

#### Feature Importance
In this section we compute the average feature importance for each feature in the divorce dataset by running the RandomForestClassifier from sci-kit learn 100 times and averaging the feature importance for each feature across all 100 runs. We then plot the average feature importance for each feature in the dataset.

In [36]:
iterations = 10000

# Randomly split the data into training and validation sets
train_X, val_X, train_y, val_y = train_test_split(X, t, test_size=0.33)

# Create empty array to hold feature importances
feature_importances_values = np.zeros((iterations, len(train_X.columns)))

# Create the random forest model and save the feature importances
for i in range(iterations):
    rf = RandomForestClassifier(n_estimators=100, max_depth=5)
    rf.fit(train_X, train_y)
    feature_importances_values[i,:] = rf.feature_importances_

# Create a dataframe of the mean feature importances
feature_importances_df = pd.DataFrame({
    'feature':train_X.columns,
    'importance':feature_importances_values.mean(axis=0)
}).sort_values('importance',ascending=False)

display(feature_importances_df.head(10))

   feature  importance
17     Q18    0.095916
39     Q40    0.071994
18     Q19    0.066364
25     Q26    0.064343
19     Q20    0.064011
8       Q9    0.061889
10     Q11    0.061301
15     Q16    0.058346
28     Q29    0.043989
27     Q28    0.039828

In [37]:
display(feature_importances_df)

   feature  importance
17     Q18    0.095916
39     Q40    0.071994
18     Q19    0.066364
25     Q26    0.064343
19     Q20    0.064011
8       Q9    0.061889
10     Q11    0.061301
15     Q16    0.058346
28     Q29    0.043989
27     Q28    0.039828
38     Q39    0.036619
16     Q17    0.034231
13     Q14    0.032398
20     Q21    0.029765
26     Q27    0.019308
1       Q2    0.017007
29     Q30    0.016999
35     Q36    0.015969
14     Q15    0.015626
24     Q25    0.014250
11     Q12    0.014139
21     Q22    0.011991
7       Q8    0.011773
36     Q37    0.011506
43     Q44    0.008736
37     Q38    0.008647
4       Q5    0.008559
3       Q4    0.006791
40     Q41    0.006398
32     Q33    0.006216
9      Q10    0.005445
0       Q1    0.005222
22     Q23    0.004629
2       Q3    0.004054
33     Q34    0.003862
23     Q24    0.003681
12     Q13    0.002700
31     Q32    0.002516
53     Q54    0.002204
48     Q49    0.001736
49     Q50    0.001337
51     Q52    0.001166
30     Q31    0.001033
34     Q35    0.000763
44     Q45    0.000710
52     Q53    0.000690
41     Q42    0.000670
5       Q6    0.000484
50     Q51    0.000461
42     Q43    0.000458
45     Q46    0.000434
47     Q48    0.000311
46     Q47    0.000304
6       Q7    0.000224