## Random Forest Feature Importance
In this notebook we use random forest modeling (an ensemble method building upon decision trees) to evaluate the feature importance of our dataset. We are doing this instead of calculating feature importance on our knn model because we have been unable to calculate feature importance for the divorce dataset on the knn model. We are using the random forest model from SciKit Learn.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# Import divorce data
divorce = pd.read_csv('data/divorce_data.csv',sep=';')

# Processing features:
X = divorce.drop('Divorce',axis=1) # .dropna() - dataset has no missing values
t = divorce['Divorce']

# Display summary statistics for the features
print(f"These are the summary statistics for the features:\n {X.describe()}")
print("--------------------------------------------------------------------")
print(f"This is the number of rows in the dataset: {len(X)}")
print("--------------------------------------------------------------------")
print(f"This is the number of unique values in each column:\n {X.nunique()}")

These are the summary statistics for the features:
                Q1          Q2          Q3          Q4          Q5          Q6  \
count  170.000000  170.000000  170.000000  170.000000  170.000000  170.000000
mean     1.776471    1.652941    1.764706    1.482353    1.541176    0.747059
std      1.627257    1.468654    1.415444    1.504327    1.632169    0.904046
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000
25%      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000
50%      2.000000    2.000000    2.000000    1.000000    1.000000    0.000000
75%      3.000000    3.000000    3.000000    3.000000    3.000000    1.000000
max      4.000000    4.000000    4.000000    4.000000    4.000000    4.000000

               Q7          Q8          Q9         Q10  ...         Q45  \
count  170.000000  170.000000  170.000000  170.000000  ...  170.000000
mean     0.494118    1.452941    1.458824    1.576471  ...    2.458824
std      0.898698    1.546371    1.557976    1.421529  ...    1.499925
min      0.000000    0.000000    0.000000    0.000000  ...    0.000000
25%      0.000000    0.000000    0.000000    0.000000  ...    1.000000
50%      0.000000    1.000000    1.000000    2.000000  ...    3.000000
75%      1.000000    3.000000    3.000000    3.000000  ...    4.000000
max      4.000000    4.000000    4.000000    4.000000  ...    4.000000

              Q46         Q47         Q48         Q49         Q50         Q51  \
count  170.000000  170.000000  170.000000  170.000000  170.000000  170.000000
mean     2.552941    2.270588    2.741176    2.382353    2.429412    2.476471
std      1.371786    1.586841    1.137348    1.511587    1.405090    1.260238
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000
25%      2.000000    1.000000    2.000000    1.000000    1.000000    2.000000
50%      3.000000    2.000000    3.000000    3.000000    2.000000    3.000000
75%      4.000000    4.000000    4.000000    4.000000    4.000000    4.000000
max      4.000000    4.000000    4.000000    4.000000    4.000000    4.000000

              Q52         Q53         Q54
count  170.000000  170.000000  170.000000
mean     2.517647    2.241176    2.011765
std      1.476537    1.505634    1.667611
min      0.000000    0.000000    0.000000
25%      1.000000    1.000000    0.000000
50%      3.000000    2.000000    2.000000
75%      4.000000    4.000000    4.000000
max      4.000000    4.000000    4.000000

[8 rows x 54 columns]
--------------------------------------------------------------------
This is the number of rows in the dataset: 170
--------------------------------------------------------------------
This is the number of unique values in each column:
 Q1     5
Q2     5
Q3     5
Q4     5
Q5     5
Q6     5
Q7     5
Q8     5
Q9     5
Q10    5
Q11    5
Q12    5
Q13    5
Q14    5
Q15    5
Q16    5
Q17    5
Q18    5
Q19    5
Q20    5
Q21    5
Q22    5
Q23    5
Q24    5
Q25    5
Q26    5
Q27    5
Q28    5
Q29    5
Q30    5
Q31    5
Q32    5
Q33    5
Q34    5
Q35    5
Q36    5
Q37    5
Q38    5
Q39    5
Q40    5
Q41    5
Q42    5
Q43    5
Q44    5
Q45    5
Q46    5
Q47    5
Q48    5
Q49    5
Q50    5
Q51    5
Q52    5
Q53    5
Q54    5
dtype: int64

#### Train-Test Split

In [3]:
# Done with sklearn
from sklearn.model_selection import train_test_split

# Split the data into training and validation sets
train_X, val_X, train_y, val_y = train_test_split(X, t, test_size=0.33, random_state=42)

# Print the train X and y shapes
print(f"Train X shape: {train_X.shape}")
print(f"Train y shape: {train_y.shape}")

# Print the summary statistics of the training features and testing features
print(f"Train X summary statistics:\n {train_X.describe()}")
print("--------------------------------------------------------------------")
print(f"Test X summary statistics:\n {val_X.describe()}")

Train X shape: (113, 54)
Train y shape: (113,)
Train X summary statistics:
                Q1          Q2          Q3          Q4          Q5          Q6  \
count  113.000000  113.000000  113.000000  113.000000  113.000000  113.000000
mean     1.725664    1.522124    1.672566    1.442478    1.460177    0.796460
std      1.604947    1.414828    1.423291    1.511492    1.581339    0.927355
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000
25%      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000
50%      2.000000    2.000000    2.000000    1.000000    1.000000    1.000000
75%      3.000000    3.000000    3.000000    3.000000    3.000000    1.000000
max      4.000000    4.000000    4.000000    4.000000    4.000000    4.000000

               Q7          Q8          Q9         Q10  ...         Q45  \
count  113.000000  113.000000  113.000000  113.000000  ...  113.000000
mean     0.477876    1.336283    1.380531    1.530973  ...    2.353982
std      0.835564    1.503630    1.542948    1.414660  ...    1.557931
min      0.000000    0.000000    0.000000    0.000000  ...    0.000000
25%      0.000000    0.000000    0.000000    0.000000  ...    1.000000
50%      0.000000    0.000000    0.000000    2.000000  ...    3.000000
75%      1.000000    3.000000    3.000000    3.000000  ...    4.000000
max      4.000000    4.000000    4.000000    4.000000  ...    4.000000

              Q46         Q47         Q48         Q49         Q50         Q51  \
count  113.000000  113.000000  113.000000  113.000000  113.000000  113.000000
mean     2.530973    2.221239    2.716814    2.424779    2.442478    2.486726
std      1.401981    1.640636    1.137581    1.462662    1.407493    1.240068
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000
25%      2.000000    1.000000    2.000000    1.000000    1.000000    2.000000
50%      3.000000    2.000000    3.000000    3.000000    3.000000    3.000000
75%      4.000000    4.000000    4.000000    4.000000    4.000000    4.000000
max      4.000000    4.000000    4.000000    4.000000    4.000000    4.000000

              Q52         Q53         Q54
count  113.000000  113.000000  113.000000
mean     2.557522    2.274336    2.000000
std      1.475624    1.453123    1.642081
min      0.000000    0.000000    0.000000
25%      1.000000    1.000000    0.000000
50%      3.000000    2.000000    2.000000
75%      4.000000    4.000000    4.000000
max      4.000000    4.000000    4.000000

[8 rows x 54 columns]
--------------------------------------------------------------------
Test X summary statistics:
               Q1         Q2         Q3         Q4         Q5         Q6  \
count  57.000000  57.000000  57.000000  57.000000  57.000000  57.000000
mean    1.877193   1.912281   1.947368   1.561404   1.701754   0.649123
std     1.680457   1.550123   1.394134   1.500209   1.731689   0.855470
min     0.000000   0.000000   0.000000   0.000000   0.000000   0.000000
25%     0.000000   0.000000   1.000000   0.000000   0.000000   0.000000
50%     2.000000   2.000000   2.000000   2.000000   1.000000   0.000000
75%     3.000000   3.000000   3.000000   3.000000   3.000000   1.000000
max     4.000000   4.000000   4.000000   4.000000   4.000000   3.000000

              Q7         Q8         Q9        Q10  ...        Q45        Q46  \
count  57.000000  57.000000  57.000000  57.000000  ...  57.000000  57.000000
mean    0.526316   1.684211   1.614035   1.666667  ...   2.666667   2.596491
std     1.019546   1.616410   1.589636   1.443376  ...   1.367131   1.320980
min     0.000000   0.000000   0.000000   0.000000  ...   0.000000   0.000000
25%     0.000000   0.000000   0.000000   0.000000  ...   2.000000   2.000000
50%     0.000000   2.000000   1.000000   2.000000  ...   3.000000   3.000000
75%     1.000000   3.000000   3.000000   3.000000  ...   4.000000   4.000000
max     4.000000   4.000000   4.000000   4.000000  ...   4.000000   4.000000

             Q47        Q48        Q49        Q50        Q51        Q52  \
count  57.000000  57.000000  57.000000  57.000000  57.000000  57.000000
mean    2.368421   2.789474   2.298246   2.403509   2.456140   2.438596
std     1.483620   1.145439   1.614277   1.412440   1.310264   1.488258
min     0.000000   0.000000   0.000000   0.000000   0.000000   0.000000
25%     1.000000   2.000000   1.000000   1.000000   2.000000   1.000000
50%     2.000000   3.000000   3.000000   2.000000   3.000000   3.000000
75%     4.000000   4.000000   4.000000   4.000000   4.000000   4.000000
max     4.000000   4.000000   4.000000   4.000000   4.000000   4.000000

             Q53        Q54
count  57.000000  57.000000
mean    2.175439   2.035088
std     1.616023   1.731689
min     0.000000   0.000000
25%     1.000000   0.000000
50%     3.000000   2.000000
75%     4.000000   4.000000
max     4.000000   4.000000

[8 rows x 54 columns]

#### Random Forest Model
Here we'll instantiate and train a Random Forest model using SciKit Learn's RandomForestClassifier. We'll use default parameters.

In [38]:
from sklearn.ensemble import RandomForestClassifier

# NOTE: uncomment the following line if you want to have random datasets each time you run the code
# train_X, val_X, train_y, val_y = train_test_split(X, t, test_size=0.33)

rf = RandomForestClassifier(n_estimators=100, max_depth=5, random_state=42)

# Fit the model
rf.fit(train_X, train_y)

# Print the training and testing accuracies
print(f"Train accuracy: {rf.score(train_X, train_y)}")
print(f"Test accuracy: {rf.score(val_X, val_y)}")

# Get feature importances from our random forest model
importances = rf.feature_importances_

# Display the importances sorted in descending order in a dataframe
feature_importances = pd.DataFrame({
    'feature':train_X.columns,
    'importance':importances
}).sort_values('importance',ascending=False)

display(feature_importances.head())

Train accuracy: 1.0
Test accuracy: 0.9473684210526315

   feature  importance
18     Q19    0.113061
17     Q18    0.097929
27     Q28    0.088157
10     Q11    0.087821
25     Q26    0.079229

#### Feature Importance
In this section we compute the average feature importance for each feature in the divorce dataset by running the RandomForestClassifier from sci-kit learn 100 times and averaging the feature importance for each feature across all 100 runs. We then plot the average feature importance for each feature in the dataset.

In [6]:
iterations = 100

# Randomly split the data into training and validation sets
train_X, val_X, train_y, val_y = train_test_split(X, t, test_size=0.33)

# Create empty array to hold feature importances
feature_importances_values = np.zeros((iterations, len(train_X.columns)))

# Create the random forest model and save the feature importances
for i in range(iterations):
    rf = RandomForestClassifier(n_estimators=100, max_depth=5)
    rf.fit(train_X, train_y)
    feature_importances_values[i,:] = rf.feature_importances_

# Create a dataframe of the mean feature importances
feature_importances_df = pd.DataFrame({
    'feature':train_X.columns,
    'importance':feature_importances_values.mean(axis=0)
}).sort_values('importance',ascending=False)

display(feature_importances_df.head(10))

   feature  importance
16     Q17    0.092472
17     Q18    0.087447
10     Q11    0.087015
39     Q40    0.082087
11     Q12    0.071113
19     Q20    0.069189
18     Q19    0.056286
15     Q16    0.049795
25     Q26    0.039377
8       Q9    0.036999

In [8]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neighbors import NearestNeighbors
from sklearn import train_test_split

n_features = 10

# Store top ten features in a Pandas dataframe
key_features = pd.DataFrame(feature_importances_df.head(10)).drop('importance', axis=1)

   feature
16     Q17
17     Q18
10     Q11
39     Q40
11     Q12
19     Q20
18     Q19
15     Q16
25     Q26
8       Q9